[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "shanghai"
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" },{ access = "read", path = "./functions-toolkit" }]

[etherscan]
unknown_chain = { key = "${TENDERLY_KEY}", chain = 882799, url = "${RPC_TENDERLY}/verify/etherscan" }

[fuzz]
runs = 10000

[invariant]
runs = 128
depth = 128
fail_on_revert = true